rails_frontend:
  image: gruntwork/rails-frontend:v1
  volumes:
    - ./rails-frontend:/usr/src/app
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=development
  links:
    - sinatra_backend:sinatra_backend

sinatra_backend:
  image: gruntwork/sinatra-backend:v1
  volumes:
    - ./sinatra-backend:/usr/src/app
  ports:
    - "4567:4567"
  environment:
    - RACK_ENV=development